# Generated by Django 3.1.1 on 2020-09-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
